/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hillary
 */

import javax.swing.*;
import java.awt.event.*;
public class Store extends javax.swing.JFrame {

    /**
     * Creates new form Store
     */
    public Store() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblArrow2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnPurchase = new javax.swing.JButton();
        lblBorder = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();
        lblMessageBox = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        jLabel2.setText("Welcome to Dota 3 Store");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblArrow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/New Piskel (12).gif"))); // NOI18N
        getContentPane().add(lblArrow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 130, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/New Piskel (12).gif"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 130, 70));

        btnMenu.setBackground(new java.awt.Color(255, 204, 51));
        btnMenu.setFont(new java.awt.Font("Baskerville Old Face", 1, 12)); // NOI18N
        btnMenu.setText("MAIN MENU");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 650, 130, 60));

        btnInventory.setBackground(new java.awt.Color(255, 204, 51));
        btnInventory.setFont(new java.awt.Font("Baskerville Old Face", 1, 12)); // NOI18N
        btnInventory.setText("INVENTORY");
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 130, 60));

        btnPurchase.setBackground(new java.awt.Color(255, 204, 51));
        btnPurchase.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnPurchase.setText("PURCHASE");
        btnPurchase.setToolTipText("");
        getContentPane().add(btnPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 670, -1, 40));

        lblBorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Untitled_design_6.png"))); // NOI18N
        lblBorder.setText("jLabel5");
        getContentPane().add(lblBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 910, 550));

        lblWelcome.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        lblWelcome.setText("Welcome to the secret shop");
        getContentPane().add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 220, 30));

        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/character.gif"))); // NOI18N
        lblAvatar.setText("jLabel1");
        getContentPane().add(lblAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 240, 270));

        lblMessageBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/dialogue1.gif"))); // NOI18N
        getContentPane().add(lblMessageBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 590, 420));

        lblBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/store.jpg"))); // NOI18N
        lblBackground.setToolTipText("");
        lblBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Menu menu = new Menu();
        menu.show();
        dispose();
        
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Store().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblArrow2;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBorder;
    private javax.swing.JLabel lblMessageBox;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
